baseURL = "http://example.org/"
languageCode = "en-us"
title = "Nathan Files Blog"
theme = "simple-hugo-theme"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  # Header
  [[menu.main]]
    url = "/posts/"
    name = "blog"
    weight = 1
  [[menu.main]]
    url = "/about/"
    name = "about"
    weight = 2
  [[menu.main]]
    url = "/contact/"
    name = "contact"
    weight = 3

  # Footer
  [[menu.footer]]
    url = "https://github.com/nfiles"
    name = "GitHub"
    weight = 1
  [[menu.footer]]
    url = "/index.xml"
    name = "RSS"
    weight = 2

[permalinks]
  post = "/post/:year/:month/:title/"

[params]
  datefmt = "Jan 2, 2006"
